apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-minus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc-minus
  template:
    metadata:
      labels:
        app: calc-minus
    spec:
      containers:
        - image: yu3papa/calc-minus:1.0
          name: main

