apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc-front
  template:
    metadata:
      labels:
        app: calc-front
    spec:
      containers:
        - image: yu3papa/calc-front:1.0
          name: main

